config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'posts#index'
  resources :posts, only: %i(index show)
end

app/models/Post.rb
class Post
  include Mongoid::Document
  field :title, type: String
  field :body, type: Text
end

app/models/Tweet.rb
class Tweet < Post
  field :body, type: Text
end

app/models/article.rb
class Article < Post
  field :reviewer, type: String
  field :keywords, type: Array
end

app/models/event.rb
class Event < Post
  field :date, type: Date
  field :place, type: String
  field :manager, type: String
end

app/models/post.rb
class Post
  include Mongoid::Document
  field :title, type: String
  field :body, type: String
  field :prepared_by, type: String
  field :is_approved, type: Boolean
end

app/models/tweet.rb
class Tweet < Post
  field :tweet_id, type: String
  field :source, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    # @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mongo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.slim
#wrapper
  h1 Posts
.toggles
  button#showall Show All
  button#tweets Tweets
  button#articles Articles
  button#events Events
.posts
  = render @posts

app/views/posts/_post.html.slim
.post class="#{post.class.to_s.downcase}s"
  = post.title
  = link_to 'Show', post_path(post)

app/views/posts/index.html.slim
#wrapper
  h1 Posts
.toggles
  button#showall Show All
  button#tweets Tweets
  button#articles Articles
  button#events Events
.posts = render partial: 'post', collection: @posts, as: :post

app/views/posts/show.html.slim
h1 = "#{@post.class.to_s} Show"
.page-header
  = link_to posts_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
p
  - @post.attribute_names.delete_if{|a| a=~ /^_/}.each do |attribute|
    strong = attribute
    = ": #{@post.public_send(attribute)}"
    br